import { useState } from "react";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import houseForm from "../public/img/house-form.png";
import { useRouter } from "next/router";
import Swal from "sweetalert2";

const Login = () => {
  const router = useRouter();

  const [email, setEmail] = useState("");
  const [contrasena, setContrasena] = useState("");
  const [mensajeError, setMensajeError] = useState("");

  const handleSubmit = async (eventoSubmit) => {
    eventoSubmit.preventDefault();

    const nuevoUsuario = {
      email,
      contrasena,
    };

    const baseUrl = "http://localhost:3000";
    const url = baseUrl + "/login";
    const fetchConfig = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(nuevoUsuario),
    };

    try {
      const respuesta = await fetch(url, fetchConfig);
      // si la respuesta no es OK
      if (!respuesta.ok) {
        // gestionar error o mensajes recibidos
        console.error("La respuesta no está OK");
        setMensajeError(
          "Error al iniciar sesión. Por favor, revisa tus credenciales e inténtalo de nuevo."
        );
        return;
      }

      // en caso de exito
      const objetoJson = await respuesta.json();
      console.dir(objetoJson);

      const usuario = objetoJson.usuario;
      // caso éxito

      // guardo datos del usuario y TOKEN
      localStorage.setItem("usuario", JSON.stringify(usuario));
      // redirijo a página protegida
      Swal.fire({
        icon: "success",
        title: "Sesión iniciada exitosamente",
        text: "Ya puedes enviar tu solicitud de cotización",
      });
      router.push("/contacto");
    } catch (error) {
      // gestion errores
      console.error(error.code);
      console.error(error.message);
      setMensajeError(
        "Error al iniciar sesión. Por favor, revisa tus credenciales e inténtalo de nuevo."
      );
    }
  };

  return (
    <>
      <Head>
        <title>Iniciar sesión</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="form-container">
          <div className="form-img">
            <Image
              height={241}
              width={322}
              src={houseForm}
              alt="Modelo de casa"
              className="form-img01"
            />
          </div>
          <div className="div-form">
            <h2>
              Inicia sesión en <strong>ModelHome</strong>
            </h2>
            <form className="form-container2" onSubmit={handleSubmit}>
              <fieldset>
                <p>Datos personales</p>
                <div>
                  <label htmlFor="email">Email</label>
                  <input
                    type="text"
                    id="email"
                    name="email"
                    value={email}
                    onChange={(evento) => setEmail(evento.target.value)}
                  />
                </div>
                <div>
                  <label htmlFor="contrasena">Contraseña</label>
                  <input
                    type="password"
                    id="contrasena"
                    name="contrasena"
                    required // campo requerido
                    minLength={8} // mínimo 8 caracteres
                    value={contrasena} // muestra el valor ingresado por el usuario
                    onChange={(e) => setContrasena(e.target.value)} // actualiza el estado cuando cambia el valor del campo
                  />
                </div>
                <div className="botones">
                  <button className="boton bg-success submit" type="submit">
                    Iniciar sesión
                  </button>
                </div>
              </fieldset>
            </form>
          </div>
        </section>
      </Layout>
    </>
  );
};
export default Login;

// import Layout from "@/components/Layout";
// import Head from "next/head";
// import Image from "next/image";
// import houseForm from "../public/img/house-form.png";
// import { useState, useContext, useEffect } from "react";
// import { useRouter } from "next/router";
// import AuthContext from "../context/authContext";

// const Login = () => {
//   const [email, setEmail] = useState("");
//   const [password, setPassword] = useState("");
//   const router = useRouter();
//   const { currentUser, login } = useContext(AuthContext);

//   useEffect(() => {
//     if (currentUser) {
//       router.push("/");
//     }
//   }, [currentUser]);

//   const handleLogin = async (e) => {
//     e.preventDefault();
//     try {
//       await login(email, password);
//     } catch (error) {
//       console.log(error);
//     }
//   };

//   return (
//     <>
//       <Head>
//         <title>Iniciar sesión</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//         <link rel="preconnect" href="https://fonts.googleapis.com" />
//         <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
//         <link
//           href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;500;600&display=swap"
//           rel="stylesheet"
//         />
//       </Head>
//       <Layout>
//         <div className="form-container">
//           <div className="form-img">
//             <Image
//               height={241}
//               width={322}
//               src={houseForm}
//               alt="Modelo de casa"
//               className="form-img01"
//             />
//           </div>
//           <div className="div-form">
//             <h2>
//               Inicia sesión en <strong>ModelHome</strong>
//             </h2>
//             <form onSubmit={handleLogin} className="form-container2">
//               <fieldset>
//                 <p>Datos personales</p>
//                 <div>
//                   <label htmlFor="email">Email</label>
//                   <input
//                     type="text"
//                     id="email"
//                     name="email"
//                     value={email}
//                     onChange={(e) => setEmail(e.target.value)}
//                   />
//                 </div>
//                 <div>
//                   <label htmlFor="contrasena">Contraseña</label>
//                   <input
//                     type="password"
//                     id="contrasena"
//                     name="contrasena"
//                     value={password}
//                     onChange={(e) => setPassword(e.target.value)}
//                   />
//                 </div>
//                 <div className="botones">
//                   <button className="boton bg-success submit" type="submit">
//                     Iniciar sesión
//                   </button>
//                 </div>
//               </fieldset>
//             </form>
//           </div>
//         </div>
//       </Layout>
//     </>
//   );
// };

// export default Login;
